# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190525_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='document',
            field=models.FileField(upload_to=b"<django.core.files.storage.FileSystemStorage object at 0x7f60660c0ed0><class 'mysite.core.models.Profile'>"),
        ),
        migrations.AlterField(
            model_name='query',
            name='document',
            field=models.FileField(upload_to=b"<django.core.files.storage.FileSystemStorage object at 0x7f60660c0e90><class 'mysite.core.models.Profile'>"),
        ),
    ]
